#!/usr/bin/env python3
"""
DeFi Trading System - Optimized Production Launcher
Auto-generated by ML optimizer
"""

import asyncio
import sys
import os

# Add core modules to path
sys.path.append(os.path.join(os.path.dirname(__file__), 'core'))
sys.path.append(os.path.join(os.path.dirname(__file__), 'intelligence'))
sys.path.append(os.path.join(os.path.dirname(__file__), 'security'))
sys.path.append(os.path.join(os.path.dirname(__file__), 'infrastructure'))

try:
    from core.engine.pipeline import main_pipeline
except ImportError:
    # Fallback import paths
    try:
        from pipeline import main_pipeline
    except ImportError:
        print("❌ Could not import main pipeline. Check your setup.")
        sys.exit(1)

if __name__ == "__main__":
    print("🚀 Starting DeFi Momentum Trading System")
    try:
        asyncio.run(main_pipeline())
    except KeyboardInterrupt:
        print("\n⏹️ Trading system stopped by user")
    except Exception as e:
        print(f"💥 System error: {e}")
        sys.exit(1)
