#!/bin/bash
# Quick Setup Script - Auto-generated by ML optimizer

echo "🚀 Setting up DeFi Trading System..."

# Install requirements
pip install -r requirements.txt

# Setup wallet if needed
if [ ! -f .env ]; then
    echo "📝 Setting up wallet..."
    python scripts/setup_wallet.py 2>/dev/null || echo "⚠️ Could not auto-setup wallet"
fi

# Run system validation
echo "🔍 Validating system..."
python scripts/minimal_test.py 2>/dev/null || echo "⚠️ Some tests failed"

echo "✅ Setup complete! Run: python main_optimized.py"
