alchemy:
  api_key_env: ALCHEMY_API_KEY
  batch_size: 100
  rate_limit_per_second: 25
  timeout_seconds: 30
dex_endpoints:
  arbitrum:
    camelot: https://api.thegraph.com/subgraphs/name/camelotlabs/camelot-amm
    uniswap: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3-arbitrum
  optimism:
    uniswap: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3-optimism
  polygon:
    pancakeswap: https://api.thegraph.com/subgraphs/name/pancakeswap/exchange-v3-polygon
    uniswap: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3-polygon
ml:
  batch_inference_size: 256
  batch_size: 32
  ensemble_weights:
  - 0.6
  - 0.4
  entropy_threshold: 0.8
  feature_cache_size: 10000
  feature_window: 60
  inference_timeout: 0.1
  learning_rate: 0.0001
  model_path: models/momentum_model.tflite
  model_update_frequency: 3600
  prediction_confidence: 0.75
  retrain_threshold: 500
monitoring:
  backup_count: 5
  health_check_interval: 60
  log_level: INFO
  max_log_size_mb: 100
  metrics_port: 8001
network_config:
  arbitrum:
    chain_id: 42161
    confirmation_blocks: 1
    default_gas_limit: 500000
    gas_multiplier: 1.1
    max_gas_price_gwei: 100
    max_retries: 3
    priority_fee: 0.1
    rpc_timeout: 30
  optimism:
    chain_id: 10
    confirmation_blocks: 1
    default_gas_limit: 500000
    gas_multiplier: 1.05
    max_gas_price_gwei: 100
    max_retries: 3
    priority_fee: 0.001
    rpc_timeout: 30
  polygon:
    chain_id: 137
    confirmation_blocks: 20
    default_gas_limit: 500000
    gas_multiplier: 1.2
    max_gas_price_gwei: 100
    max_retries: 3
    priority_fee: 30
    rpc_timeout: 30
performance:
  cache_ttl_seconds: 30
  health_check_interval: 60
  max_concurrent_requests: 10
  prediction_timeout: 5
  trade_execution_timeout: 30
redis:
  host: localhost
  port: 6379
risk:
  base_position_size: 0.001
  confidence_level: 0.95
  kelly_multiplier: 0.25
  max_gas_budget: 0.005
  max_portfolio_exposure: 0.01
  max_position_size: 0.002
  min_liquidity: 100000
  min_position_size: 0.0001
safety:
  contract_min_size: 100
  enable_mev_protection: true
  enable_rug_protection: true
  honeypot_timeout: 10
  max_pending_txs: 5
  min_liquidity: 100000
scanning:
  batch_size: 100
  concurrent_requests: 50
  max_tokens_per_scan: 10000
  min_liquidity_usd: 250000
  min_volume_usd: 1000000
  scan_interval_seconds: 30
trading:
  base_position_size: 0.001
  breakout_timeframe: 60
  decay_threshold: 0.005
  enable_live_trading: false
  max_holding_time: 1800
  max_slippage: 0.03
  min_volume_spike: 2.5
  momentum_threshold: 0.09
  position_monitor_interval: 5
  stop_loss_threshold: 0.02
  take_profit_threshold: 0.15
  velocity_threshold: 0.13
