groups:
  - name: defi-trading-alerts
    rules:
      - alert: TradingSystemDown
        expr: up{job="trading-system"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "DeFi Trading System is down"
          description: "The trading system has been down for more than 1 minute"
      
      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{name="defi-trading"} / container_spec_memory_limit_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 80% for 5+ minutes"
      
      - alert: ModelInferenceLatencyHigh
        expr: histogram_quantile(0.95, rate(predict_request_processing_seconds_bucket[5m])) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Model inference latency too high"
          description: "P95 model inference latency is above 1 second"
      
      - alert: TradingErrorRate
        expr: rate(api_errors_total[5m]) / rate(predictions_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High trading error rate"
          description: "Trading error rate is above 10% for 5+ minutes"
      
      - alert: WalletBalanceLow
        expr: wallet_balance_eth < 0.005
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Wallet balance is low"
          description: "Wallet balance is below 0.005 ETH"
      
      - alert: RugpullRiskHigh
        expr: rugpull_risk_score > 0.8
        for: 0s
        labels:
          severity: warning
        annotations:
          summary: "High rugpull risk detected"
          description: "Token {{$labels.token}} has high rugpull risk score"
