# Renaissance Production Configuration
system:
  name: "Renaissance DeFi Trading System"
  version: "2.0.0"
  mode: "production"
  environment: "production"
  
performance_targets:
  tokens_per_day: 15000
  signals_per_hour: 100
  trades_per_hour: 25
  target_roi_daily: 0.05
  max_drawdown: 0.08
  
ml_config:
  model_type: "transformer"
  sequence_length: 120
  attention_heads: 12
  layers: 8
  d_model: 512
  batch_size: 64
  learning_rate: 0.0001
  
trading:
  starting_capital: 10.0
  max_position_size: 15.0
  max_daily_loss: 25.0
  confidence_threshold: 0.85
  momentum_threshold: 0.75
  
chains:
  - name: "arbitrum"
    rpc: "https://arb1.arbitrum.io/rpc"
    chain_id: 42161
    gas_multiplier: 1.1
  - name: "polygon"
    rpc: "https://polygon-rpc.com"
    chain_id: 137
    gas_multiplier: 1.2
  - name: "optimism"
    rpc: "https://mainnet.optimism.io"
    chain_id: 10
    gas_multiplier: 1.1

api_config:
  rate_limits:
    dexscreener: 300
    gecko_terminal: 500
    honeypot_is: 100
    twitter: 450
    etherscan: 5
  
monitoring:
  prometheus_port: 8090
  grafana_port: 3000
  api_port: 8000
  dashboard_port: 8080
