system:
  name: "Renaissance DeFi Trading System"
  version: "4.0.0"
  intelligence_level: "quant_grade"
  target_performance: "exponential_growth"
  
scanning:
  target_tokens_per_day: 10000
  parallel_workers: 100
  websocket_streams: 6
  momentum_detection_threshold: 0.8
  
model:
  architecture: "transformer_ensemble"
  num_attention_heads: 8
  ensemble_size: 5
  confidence_threshold: 0.85
  
execution:
  max_latency_seconds: 30
  mev_protection_level: 4
  kelly_position_sizing: true
