system:
  name: "Renaissance DeFi Trading System"
  version: "2.0.0"
  mode: "production"

trading:
  confidence_threshold: 0.75
  momentum_threshold: 0.65
  volatility_threshold: 0.10
  liquidity_threshold: 50000
  min_liquidity_threshold: 10000
  max_risk_score: 0.4
  honeypot_risk_threshold: 0.3
  max_slippage: 0.03
  stop_loss_threshold: 0.05
  take_profit_threshold: 0.12
  max_hold_time: 300
  min_hold_time: 30
  min_price_change: 9
  max_price_change: 15
  price_momentum_decay: 0.95
  max_position_size: 1.0
  starting_capital: 10.0
  kelly_multiplier: 0.25
  max_correlation: 0.6
  order_flow_threshold: 0.3
  microstructure_noise_limit: 0.1
  jump_intensity_threshold: 0.2
  sentiment_threshold: 0.6
  social_momentum_weight: 0.2
  whale_threshold: 100000
  max_gas_price: 50
  mev_protection_threshold: 0.01
  flashbots_threshold: 1.0
  regime_change_threshold: 0.7
  volatility_regime_threshold: 0.15
  trend_regime_threshold: 0.05
  sharpe_target: 2.0
  max_drawdown_limit: 0.15
  win_rate_target: 0.6
  roi_target: 0.15

security:
  enable_real_trading: false
  dry_run_mode: true
  max_daily_trades: 1000
  emergency_stop_enabled: true

chains:
  ethereum:
    enabled: true
    priority: 1
    min_gas_price: 10
    max_gas_price: 100
  arbitrum:
    enabled: true
    priority: 2
    min_gas_price: 0.1
    max_gas_price: 2
  polygon:
    enabled: true
    priority: 3
    min_gas_price: 20
    max_gas_price: 200
  optimism:
    enabled: false
    priority: 4
    min_gas_price: 0.001
    max_gas_price: 0.1

scanning:
  parallel_workers: 500
  websocket_workers: 100
  refresh_interval: 0.5
  batch_size: 1000
  cache_ttl: 15
  max_tokens_per_scan: 50000

model:
  type: "tensorflow_lite"
  path: "models/model_weights.tflite"
  scaler_path: "models/scaler.pkl"
  features_path: "models/feature_names.json"
  retrain_threshold: 100
  confidence_decay: 0.95
  ensemble_weights: [0.4, 0.3, 0.3]

monitoring:
  performance_logging: true
  trade_logging: true
  system_metrics: true
  dashboard_port: 8080
  inference_port: 8000
  log_level: "INFO"
  max_log_size: "100MB"
  backup_logs: true